depot/config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :sessions
  resources :ratings
  resources :categories
  
  get "store/index"
  resources :products do
    get :who_bought, on: :member
    patch :disable, on: :member
    patch :enable, on: :member
  end

  root 'store#index', as: 'store'

  

end

depot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= controller.controller_name %>">
  <div id="banner">
    <%= image_tag("logo.png") %>
    <%= @page_title || "Pragmatic Bookshelf" %>
  </div>
  
  <div id="columns">
    <div id="side">

      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render @cart %>
        <% end %>
      <% end %>
      
      <% if session[:user_id] %>
        <ul>
          <li><%= link_to 'Orders',   orders_path   %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Categories', categories_path %></li>
          <li><%= link_to 'Users',    users_path    %></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete   %>
      <% else %>    
        <ul>
          <li><%= link_to 'LOG IN', login_path %></li>
        </ul>
      <% end %>

    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>

  <% flash.each do |key, value| %>
    <%= content_tag :div, value %>
  <% end %>

</body>
</html>