depot/config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :sessions
  resources :ratings
  resources :categories
  
  get "store/index"
  resources :products do
    get :who_bought, on: :member
    patch :disable, on: :member
    patch :enable, on: :member
  end

  root 'store#index', as: 'store'

  

end

depot/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :disable, :enable]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    debugger
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product,
          notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created,
          location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy

    if @product.destroy
      respond_to do |format|
        format.html { redirect_to products_url }
        format.json { head :no_content }
      end
    else
      flash[:error] = 'Product could not be deleted'
      redirect_to products_url
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end

  def disable
    @product.enabled = false
    @product.save
    redirect_to products_url
  end

  def enable
    @product.enabled = true
    @product.save
    redirect_to products_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white
    # list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :enabled, :category_id)
    end
end

depot/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select(:category_id, options_for_select(Category.pluck(:name, :id))) %>
  </div>
  <div class="field">
    <%= f.check_box(:enabled) %>
    <%= f.label('Enable the Product') %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

depot/app/views/products/edit.html.erb
  <h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %>
<%= link_to 'Back', products_path %>

depot/app/views/products/index.html.erb
<h1>Listing products</h1>

  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
  
  <table>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td>
        <%= image_tag(product.image_url, class: 'list_image') %>
      </td>
      <td class="list_description">
        <dl>
          <dt><%= product.title %></dt>
          <dd><%= truncate(strip_tags(product.description), length: 80) %></dd><br>
          <dd><strong>Category: </strong><%= Category.find(product.category_id).name %></dd>
        </dl>
      </td>
      <td class="list_actions">
        <%= link_to 'Show', product %><br/>
        <%= link_to 'Edit', edit_product_path(product) %><br/>
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %><br/>
        <% if product.enabled %>
          <%= link_to 'Disable', disable_product_path(product), method: :patch %>
        <% else %>
          <%= link_to 'Enable', enable_product_path(product), method: :patch %>
        <% end %>
      </td>
      <td>
        <%= select_tag(:rating_id, options_for_select([[0,0], [1,1], [2,2], [3,3], [4,4], [5,5], [6,6]], product.rating_by_user(session[:user_id])), class: 'rating_class', data: { product_id: product.id }) %>
        <p class="average_rating">Avg-Rating: <%= product.average_rating  %></p>
      </td>
    </tr>
  <% end %>
  </table>
<br />

<%= link_to 'New product', new_product_path %>

depot/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @product.enabled %>
</p>

<p>
  <strong>Category:</strong>
  <%= Category.find(@product.category_id).name %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>